http {
  host = "0.0.0.0"
  port = 8080
}

player-profile-client {
  uri = "https://transfermarkt-api.vercel.app"
  cache-ttl = 1 day
  failed-cache-ttl = 300 seconds
  cache-name = "transfermarkt.player-profile-client"
}

player-search-client {
  uri = "https://transfermarkt-api.vercel.app"
  cache-ttl = 1 day
  failed-cache-ttl = 300 seconds
  cache-name = "transfermarkt.player-search-client"
}

player-market-value-client {
  uri = "https://transfermarkt-api.vercel.app"
  cache-ttl = 1 day
  failed-cache-ttl = 300 seconds
  cache-name = "transfermarkt.player-market-value-client"
}

players-update-criteria {
  not-updated-for = 1 day
}

aws {
  region = "eu-west-1"
  region = ${?AWS_REGION}
  access-key = "DUMMYIDEXAMPLE"
  access-key = ${?AWS_ACCESS_KEY}
  secret-key = "DUMMYEXAMPLEKEY"
  secret-key = ${?AWS_SECRET_KEY}
}
