http {
  host = "0.0.0.0"
  port = 8080
}

; API_URL = "http://0.0.0.0:8001"
API_URL = "https://transfermarkt-api.vercel.app"

player-profile-client {
  uri = "https://transfermarkt-api.vercel.app"
  cache-ttl = 1 day
  failed-cache-ttl = 300 seconds
  cache-name = "transfermarkt.player-profile-client"
}

player-search-client {
  uri = ${?API_URL}
  cache-ttl = 1 day
  failed-cache-ttl = 300 seconds
  cache-name = "transfermarkt.player-search-client"
}

player-market-value-client {
  uri = ${?API_URL}
  cache-ttl = 1 day
  failed-cache-ttl = 300 seconds
  cache-name = "transfermarkt.player-market-value-client"
}

player-stats-client {
  uri = ${?API_URL}
  cache-ttl = 1 hour
  failed-cache-ttl = 300 seconds
  cache-name = "transfermarkt.player-stats-client"
}

club-profile-client {
  uri = ${?API_URL}
  cache-ttl = 1 day
  failed-cache-ttl = 300 seconds
  cache-name = "transfermarkt.club-profile-client"
}

club-players-client {
  uri = ${?API_URL}
  cache-ttl = 1 day
  failed-cache-ttl = 300 seconds
  cache-name = "transfermarkt.club-players-client"
}

club-search-client {
  uri = ${?API_URL}
  cache-ttl = 1 day
  failed-cache-ttl = 300 seconds
  cache-name = "transfermarkt.club-search-client"
}

players-update-criteria {
  not-updated-for = 1 day
}

login {
  token-expiry-time = 20 minutes
}

aws {
  region = "eu-west-1"
  region = ${?AWS_REGION}
  access-key = "DUMMYIDEXAMPLE"
  access-key = ${?AWS_ACCESS_KEY}
  secret-key = "DUMMYEXAMPLEKEY"
  secret-key = ${?AWS_SECRET_KEY}
  endpoint-override = "http://0.0.0.0:8000/"
}

updater-task {
  players-profile-update-every = 60 minutes
  players-value-update-every = 2 minutes
  dividend-pay-every = 1 minutes
  dividend-yield = 0.01
}
