name: CI
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
jobs:
  ci:
    # Run on external PRs, but not on internal PRs since those will be run by push to branch
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xmx4G
      DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

#      - name: Set up JDK 21
#        uses: actions/setup-java@v1
#        with:
#          java-version: 21
#
#      - name: Compile
#        run: |
#          sbt -v compile
#
#      - name: Test
#        run: |
#          sbt -v test
#
#      - name: Build Fat Jar
#        run: |
#          sbt -v assembly
#
#      - name: Build Docker image
#        run: |
#          docker build -t footballstock .
#
#      - name: Push docker image to DockerHub
#        run: |
#          docker login -u ${DOCKERHUB_LOGIN} -p ${DOCKERHUB_PASSWORD};
#          docker tag footballstock ${DOCKERHUB_LOGIN}/footballstock;
#          docker push ${DOCKERHUB_LOGIN}/footballstock;

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script:
            sudo snap install docker;
            sudo docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }};
#            take id of old image and remove it after new one is pulled
            sudo docker pull ${{ secrets.DOCKERHUB_LOGIN }}/footballstock;
            sudo docker run -d -p 80:8080 ${{ secrets.DOCKERHUB_LOGIN }}/footballstock;
            sudo docker ps;
