name: CI
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
jobs:
  ci:
    # Run on external PRs, but not on internal PRs since those will be run by push to branch
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    env:
      JAVA_OPTS: -Xmx4G
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
#      - name: Compile
#        run: |
#          sbt -v compile
#      - name: Test
#        run: |
#          sbt -v test
      - name: TESTwithACTIONS_SECRET
        run: |
          echo "${{ secrets.TEST_ACTIONS }}"
      - name: TESTwithACTIONS_VARIABLE
        run: |
          echo "${{ vars.TEST_ACTION_VARIABLE }}"
      - name: DockerVersion
        run: |
          docker --version
          

#sbt clean;
#  sbt assembly; docker build -t <app-name> .; docker tag <app-name> <dockerhub-login>/<app-name>; docker push demo42/<app-name>

